# Generated by Django 4.2.3 on 2023-07-18 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defibrillator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("address", models.TextField()),
                (
                    "coordinates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=2
                    ),
                ),
                ("available", models.BooleanField(default=False)),
                ("access_type", models.BooleanField(default=False)),
                ("access_times", models.TextField()),
            ],
        ),
    ]
