# Generated by Django 4.2.3 on 2023-08-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("defib_radar_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="defibrillator",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
