# Generated by Django 4.2.3 on 2023-07-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defib_radar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defibrillator',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='defibrillator',
            name='address_line2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defibrillator',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defibrillator',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defibrillator',
            name='zipcode',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
