# Generated by Django 4.2.3 on 2023-07-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defib_radar_app', '0002_rename_address_defibrillator_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defibrillator',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='defibrillator',
            name='access_times',
        ),
        migrations.RemoveField(
            model_name='defibrillator',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='defibrillator',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='defibrillator',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='defibrillator',
            name='latitude',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defibrillator',
            name='longitude',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
    ]
